# Cadre Player - advanced libmpv configuration
# Add raw libmpv properties here.
# Examples:
# vo=gpu-next
# hwdec=auto-safe
profile=high-quality
vo=gpu-next
gpu-api=vulkan
hwdec=nvdec
brightness=0
contrast=0
saturation=0
gamma=0
video-zoom=0.0
video-rotate=0
scale=ewa_lanczossharp
dscale=mitchell
cscale=ewa_lanczossharp
dither-depth=auto
deband=yes
deband-iterations=2
deband-threshold=48
deband-range=16
screenshot-format=png
screenshot-high-bit-depth=yes
af=loudnorm
tone-mapping=auto
